### ISSUE TITLE
Cannot join the telegram main group

### ISSUE THREAD

**Issue by JideGuru** [flutter-telegram/community-index#19]
Hi @veetaw , not sure if you remember me but I used to be an active group member circa 2018. I replicated a bunch of ui using Flutter and was promoted to group admin based on my activity.

But at some point(circa 2019) I lost my phone number/telegram account and when I joined the group with my new account I got banned because the admins thought I was impersonating my main account.

It'll be nice if I can get access back into the group. Thanks

**Comment by veetaw** [comment]
Hello! Yes I think I do remember you. What's your @username ? I will unban you. Sorry but I haven't been active on the group for a while.

**Comment by JideGuru** [comment]
Thanks for the swift response.
This is my user profile t.me/jideguru. "jideguru" is my username
